== Implementation Style of Application

The desired XMPP grid management application, described by the Use Cases and thesis task description, might be implemented in three different styles: As XMPP-server plugin, XMPP component or XMPP bot.

The implementation has a profounding impact on the implementation language and approch, and must therefore be considered very carefully as a high risk factor is involved.

To decide, which architecture style is most suited, various aspects must be taken into account:
* All required features should be supported
* Portability (e.g. to other XMPP-Servers)
* Implementation difficulty



[context and problem statement]

[decision drivers | forces | facing] _(optional)_

=== Considered Options

* As plugin for a XMPP server, e.g. a http://download.igniterealtime.org/openfire/docs/latest/documentation/plugin-dev-guide.html[Openfire Plugin].
* As XMPP component (https://xmpp.org/extensions/xep-0114.html[XEP-0114]).
* As XMPP bot (i.e., a daemon logged into a XMPP server as a normal user).

=== Decision Outcome

Chosen option: [option 1], because [justification. e.g., only option, which meets k.o. criterion decision driver | which resolves force force | ... | comes out best (see below)].

Positive Consequences: _(optional)_
  - [e.g., improvement of quality attribute satisfaction, follow-up decisions required, ...]
  - ...

Negative consequences: _(optional)_
  - [e.g., compromising quality attribute, follow-up decisions required, ...]
  - ...

=== Pros and Cons of the Options

==== Plugin

* Good, because all features could be implemented directly on the XMPP server.
* Good, because there is no additional protocol overhead and abstraction.
* Bad, because a very high coupling to a specific XMPP server is required.

==== Component

* Good, because the application type fits very well in the Components model.
* ????, because supported FEATURES?
* Bad, because the specification of Components is marked as _Historical_ and might therefore not be implemented by many XMPP Servers.
** Note: openfire supports Components
* Bad, because possibly not all XMPP client libraries implement this feature (???)

==== Bot

* Good, because a Bot is basically a normal XMPP client, which is supported by every XMPP server
* Good, because all XMPP client libraries implement this feature.
* Bad, because the application is not a normal XMPP-client but rather a Component.
* ????, because supported FEATURES?
